spring.application.name=Webshop

POSTGRESQL_DATABASENAME=webshop
POSTGRESQL_USERNAME=postgres
POSTGRESQL_PASSWORD=password

my.upload_location=uploads

spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRESQL_DATABASENAME}
spring.datasource.username=${POSTGRESQL_USERNAME}
spring.datasource.password=${POSTGRESQL_PASSWORD}

# Jpa instellingen
spring.jpa.show-sql=true

# forces to generate the data structures
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create

# database initialization with data.sql after hibernate
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB

client-id=Webshop-backend
client-secret=gqOGZIPJbfUfwvjkKMMzQHZn8NYFze0c
audience=Webshop-backend
issuer-uri=http://localhost:9090/realms/Webshop
spring.security.oauth2.resourceserver.jwt.issuer-uri= ${issuer-uri}
spring.security.oauth2.resourceserver.jwt.audiences= ${audience}